namespace DotNetRocks.FluentSPRibbon
{
    public enum FlyoutAnchorProperty
    {
        Alt,
        CacheMenuVersions,
        Command,
        CommandType,
        CommandMenuClose,
        Image16by16,
        Image16by16Class,
        Image16by16Left,
        Image16by16Top,
        Image32by32,
        Image32by32Class,
        Image32by32Left,
        Image32by32Top,
        LabelText,
        PopulateDynamically,
        PopulateQueryCommand,
        PopulateOnlyOnce,
        Sequence,
        TemplateAlias,
        ToolTipImage32by32,
        ToolTipImage32by32Class,
        ToolTipImage32by32Left, 
        ToolTipImage32by32Top,
        ToolTipTitle,
        ToolTipDescription,
        ToolTipHelpKeyWord,
        ToolTipSelectedItemTitle,
        ToolTipShortcutKey
    }
}