namespace DotNetRocks.FluentSPRibbon
{
    public enum ToggleButtonProperty
    {
        Alt,
        Command,
        CommandValueId,
        Description,
        LabelCss,
        LabelText,
        Image32by32,
        Image32by32Class,
        Image32by32Left,
        Image32by32Top,
        Image16by16,
        Image16by16Class,
        Image16by16Left,
        Image16by16Top,
        MenuItemId,
        QueryCommand,
        Sequence,
        TemplateAlias,
        ToolTipImage32by32,
        ToolTipImage32by32Class,
        ToolTipImage32by32Left,
        ToolTipImage32by32Top,
        ToolTipTitle,
        ToolTipDescription,
        ToolTipHelpKeyWord,
        ToolTipShortcutKey
    }
}